title: LeggoTM's Blog
author: LeggoTM
email: m.tanmay17@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  A simple blog to learn Github features!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
